name: Continuous Integration

on: [ push, pull_request ]

jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]

    steps:
      - name: Set deploy environment variable
        run: |
          # SPACY_LANGUAGE_DETECTION_RELEASE_BUILD is also used in setup.py
          if [ $GITHUB_REF == "refs/heads/stable" ] && \
             [ $GITHUB_EVENT_NAME == "push" ] && \
             [ ${{ matrix.python-version }} == "3.8" ]; then
            echo "SPACY_LANGUAGE_DETECTION_RELEASE_BUILD=1" >> $GITHUB_ENV
          else
            echo "SPACY_LANGUAGE_DETECTION_RELEASE_BUILD=0" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python tests/requirements_spacy.py
          pip install -r styling_requirements.txt
          python setup.py develop
      - name: Linting
        run: |
          yapf --diff --recursive spacy_language_detection/
          yapf --diff --recursive tests/
          pylint spacy_language_detection/
          pylint tests/
      - name: Test with pytest
        run: |
          python -m unittest